#!/bin/bash
# BSD 3-Clause License
#
# Copyright (c) 2021 Thomas Dreibholz <dreibh@simula.no>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


function makeDockerfile ()
{
   local file="$1"
   local from="$2"

   if docker pull "${from}" ; then
      cat >"${file}" <<EOF
FROM ${arch}/ubuntu:${ubuntu}

COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
RUN chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh
EOF
   fi
}


# Architectures for Ubuntu: https://hub.docker.com/_/ubuntu
for arch in amd64 arm32v7 arm64v8 i386 ppc64le riscv64 s390x ; do
   for ubuntu in 24.04 22.04 20.04 18.04 16.04 14.04 ; do
      # shellcheck disable=SC2001
      darch="$(echo "${arch}" | sed -e "s/arm64v8/aarch64/")"
      makeDockerfile "Dockerfile.${darch}.ubuntu${ubuntu}" "${arch}/ubuntu:${ubuntu}"
   done
done


# Architectures for Debian: https://hub.docker.com/_/debian
for arch in amd64 arm32v5 arm32v7 arm64v8 i386 mips64le ppc64le riscv64 s390x ; do
   for debian in stretch jessie buster bullseye bookworm trixie unstable ; do
      # shellcheck disable=SC2001
      darch="$(echo "${arch}" | sed -e "s/arm64v8/aarch64/")"
      makeDockerfile "Dockerfile.${darch}.${debian}" "${arch}/debian:${debian}"
   done
done


# Architectures for Fedora: https://hub.docker.com/_/fedora/
for arch in amd64 arm32v7 arm64v8 ppc64le s390x ; do
   for fedora in 33 34 35 36 37 38 39 40 rawhide latest ; do
      # shellcheck disable=SC2001
      darch="$(echo "${arch}" | sed -e "s/arm64v8/aarch64/")"
      # shellcheck disable=SC2001
      dfedora=$(echo "${fedora}" | sed -e "s/^latest/_latest/")
      makeDockerfile "Dockerfile.${darch}.fedora${dfedora}" "${arch}/fedora:${fedora}"
   done
done
