# Dockerfile for the host container
FROM ubuntu:bionic

RUN \
  sudo apt-get update -y && \
  sudo apt-get install -y qemu qemu-user-static && \
  sudo apt-get clean && \
  docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

ENTRYPOINT /bin/bash
